name: run

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: 10 16 * * *

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      
      - name: Random delay (1 minute to 2 hours)
        run: |
          MIN=60
          MAX=7200
          DELAY=$(( RANDOM % (MAX - MIN + 1) + MIN ))
          echo "Sleeping for $DELAY seconds ($((DELAY/60)) minutes)"
          sleep $DELAY
      
      - run: npm run main
        env:
          GLADOS: ${{ secrets.RAILGUN163 }}
          NOTIFY: ${{ secrets.NOTIFY }}
