name: running Workflow

on:
  schedule:
    # 每周一 00:00 UTC 运行一次
    - cron: "0 0 * * 1"

permissions:
  contents: read
  actions: write

jobs:
  keepalive-job:
    name: running Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Random delay
        run: |
          # 随机延迟
          delay=$(( (RANDOM % 271) + 30 ))
          echo "Delaying for ${delay} seconds"
          sleep $delay
        shell: bash

      - name: Keepalive noop
        run: echo "keep running"
        shell: bash
